export const QUESTIONS = [
    {
      category: "Arts & Literature",
      id: "622a1c3a7cc59eab6f95139e",
      correctAnswer: "Harry Potter",
      incorrectAnswers: [
        "Voyages Extraordinaires",
        "Percy Jackson & the Olympians",
        "Twilight",
      ],
      question: "In which book series does 'Severus Snape' appear?",
      tags: ["arts_and_literature"],
      type: "Multiple Choice",
      difficulty: "easy",
      regions: [],
    },
    {
      category: "Arts & Literature",
      id: "622a1c397cc59eab6f950ead",
      correctAnswer: "J. K. Rowling",
      incorrectAnswers: ["Christopher Tolkien", "Philip Pullman", "C. S. Lewis"],
      question: "Which author wrote 'Harry Potter and the Philosopher's Stone'?",
      tags: ["arts_and_literature"],
      type: "Multiple Choice",
      difficulty: "easy",
      regions: [],
    },
    {
      category: "Arts & Literature",
      id: "622a1c3a7cc59eab6f951364",
      correctAnswer: "Mural",
      incorrectAnswers: ["Sculpture", "Graffiti", "Mozaic"],
      question: "A large painting or decoration done on a wall is known as what?",
      tags: ["art", "words", "arts_and_literature"],
      type: "Multiple Choice",
      difficulty: "easy",
      regions: [],
    },
    {
      category: "Arts & Literature",
      id: "622a1c397cc59eab6f950eb6",
      correctAnswer: "Charles Darwin",
      incorrectAnswers: [
        "Percy Bysshe Shelley",
        "H. Rider Haggard",
        "Robert Louis Stevenson",
      ],
      question: "Which author wrote 'On the Origin of Species'?",
      tags: ["arts_and_literature"],
      type: "Multiple Choice",
      difficulty: "easy",
      regions: [],
    },
    {
      category: "Arts & Literature",
      id: "622a1c3b7cc59eab6f9513b2",
      correctAnswer: "The Hobbit",
      incorrectAnswers: [
        "Charlotte's Web",
        "Alice's Adventures in Wonderland",
        "Bluebeard",
      ],
      question: "In which book does 'Bilbo Baggins' appear?",
      tags: ["arts_and_literature"],
      type: "Multiple Choice",
      difficulty: "easy",
      regions: [],
    },
  ];